"""empty message

Revision ID: 389ea7315f12
Revises: 7f9eb0d2062c
Create Date: 2018-08-12 18:56:28.557904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '389ea7315f12'
down_revision = '7f9eb0d2062c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignment', schema=None) as batch_op:
        batch_op.drop_index('ix_assignment_date_issued')
        batch_op.drop_index('ix_assignment_due_date')
        batch_op.drop_index('ix_assignment_title')

    op.drop_table('assignment')
    op.drop_table('folders')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_admin')
        batch_op.drop_column('admin')
        batch_op.drop_column('password_hash')
        batch_op.drop_column('last_seen')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_seen', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True))
        batch_op.add_column(sa.Column('admin', sa.BOOLEAN(), nullable=True))
        batch_op.create_index('ix_user_admin', ['admin'], unique=False)

    op.create_table('folders',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('base_id', sa.VARCHAR(length=128), nullable=True),
    sa.Column('notes_id', sa.VARCHAR(length=128), nullable=True),
    sa.Column('assignments_id', sa.VARCHAR(length=128), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assignment',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=128), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('date_issued', sa.DATETIME(), nullable=True),
    sa.Column('due_date', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assignment', schema=None) as batch_op:
        batch_op.create_index('ix_assignment_title', ['title'], unique=False)
        batch_op.create_index('ix_assignment_due_date', ['due_date'], unique=False)
        batch_op.create_index('ix_assignment_date_issued', ['date_issued'], unique=False)

    # ### end Alembic commands ###
