"""empty message

Revision ID: 3901ed3ed35d
Revises: 20f15e5567b3
Create Date: 2018-06-16 11:35:31.367134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3901ed3ed35d'
down_revision = '20f15e5567b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('grade', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('username', sa.String(), nullable=True))
    op.create_index(op.f('ix_user_grade'), 'user', ['grade'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_grade'), table_name='user')
    op.drop_column('user', 'username')
    op.drop_column('user', 'grade')
    # ### end Alembic commands ###
