"""empty message

Revision ID: 5180de9d8814
Revises: a83d390fb451
Create Date: 2018-06-25 16:01:22.424423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5180de9d8814'
down_revision = 'a83d390fb451'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roster', sa.Column('team', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_roster_team'), 'roster', ['team'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roster_team'), table_name='roster')
    op.drop_column('roster', 'team')
    # ### end Alembic commands ###
