"""admin field

Revision ID: 5a985af0e191
Revises: e1827e2a7c35
Create Date: 2018-06-26 14:33:43.954251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a985af0e191'
down_revision = 'e1827e2a7c35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_admin'), ['admin'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_admin'))
        batch_op.drop_column('admin')

    # ### end Alembic commands ###
