"""empty message

Revision ID: cf6debbaaeb6
Revises: 5a985af0e191
Create Date: 2018-06-26 16:38:32.285917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf6debbaaeb6'
down_revision = '5a985af0e191'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('user3_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('user3_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
