"""empty message

Revision ID: e4d34b0c5068
Revises: cf6debbaaeb6
Create Date: 2018-06-26 20:16:56.080173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4d34b0c5068'
down_revision = 'cf6debbaaeb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tournament_id', sa.String(length=64), nullable=True))
        batch_op.drop_index('ix_event_date')
        batch_op.drop_index('ix_event_team')
        batch_op.drop_index('ix_event_tournament')
        batch_op.create_foreign_key('fk_tournament_tournament_id', 'tournament', ['tournament_id'], ['id'])
        batch_op.drop_column('tournament')
        batch_op.drop_column('date')
        batch_op.drop_column('team')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('date', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('tournament', sa.VARCHAR(length=64), nullable=True))
        batch_op.drop_constraint('fk_tournament_tournament_id', type_='foreignkey')
        batch_op.create_index('ix_event_tournament', ['tournament'], unique=False)
        batch_op.create_index('ix_event_team', ['team'], unique=False)
        batch_op.create_index('ix_event_date', ['date'], unique=False)
        batch_op.drop_column('tournament_id')

    # ### end Alembic commands ###
