"""empty message

Revision ID: e74ae3b9d636
Revises: 389ea7315f12
Create Date: 2018-08-24 17:15:02.081373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e74ae3b9d636'
down_revision = '389ea7315f12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('perm_id', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_perm_id'), ['perm_id'], unique=False)
        batch_op.drop_index('ix_user_username')
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(), nullable=True))
        batch_op.create_index('ix_user_username', ['username'], unique=1)
        batch_op.drop_index(batch_op.f('ix_user_perm_id'))
        batch_op.drop_column('perm_id')

    # ### end Alembic commands ###
