"""empty message

Revision ID: f3a858b84efa
Revises: e74ae3b9d636
Create Date: 2018-09-14 17:40:08.713274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3a858b84efa'
down_revision = 'e74ae3b9d636'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('courseWorkID', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assignment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assignment_courseWorkID'), ['courseWorkID'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignment_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignment_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assignment_name'))
        batch_op.drop_index(batch_op.f('ix_assignment_date'))
        batch_op.drop_index(batch_op.f('ix_assignment_courseWorkID'))

    op.drop_table('assignment')
    # ### end Alembic commands ###
